# Site
name: "KageSenshi's Log"
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'kagesenshi'
email: 'kagesenshi.87@gmail.com'
destination: ./docs/
include: ["_pages", ".nojekyll"]
permalink: /:year/:month/:title:output_ext

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    kagesenshi:
      id:             kagesenshi
      name:           Izhar Firdaus
      site:           https://blog.kagesenshi.org
      avatar:         assets/images/kagesenshi.jpg
      bio:            "I'm a system architect, data engineer and developer advocate with passion in Free / Open Source software, entrepreneurship, community building, education and martial art. I take enjoyment in bridging and bringing together different FOSS technologies to help businesses and organizations utilize IT infrastructure to aid and optimize their business and organizational process."
      email:          kagesenshi.87@gmail.com
      linkedin:        https://linkedin.com/in/kagesenshi
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kagesenshi
      categories: [blog]
      avatar: assets/images/anonavatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, vendor, scripts]
